name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Build docker-build
      run : docker build . -t container
      
    - name: ECR
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: loginECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: build container and tag 
      run: |
        docker build -t cnsd/album .
        docker tag cnsd/album:${{ github.run_number}} 309791011032.dkr.ecr.us-east-1.amazonaws.com/cnsd/album:${{ github.run_number}}
        docker push 309791011032.dkr.ecr.us-east-1.amazonaws.com/cnsd/album:${{ github.run_number}}
       
      
      
      
      
      
      
